### ISSUE TITLE
Docker Test Fails

### ISSUE THREAD

**Issue by tomtom87** [aragon/dao-kits#19]
I'm running `npm test` or `npm install` and getting the following errors from docker

```
> npm run docker:build && npm run docker:run && test `docker-compose ps -q | xargs docker inspect -f '{{ .Name }} {{ .State.ExitCode }}' | grep deploy | cut -d' ' -f 2` = 0


> @aragon/kits-beta@1.1.3 docker:build /Users/xxx/xxx/dao-kits/kits/beta
> docker build -t aragon/templates-beta -f Dockerfile ../..


    at Promise.all.then.arr (/Users/xxx/xxx/dao-kits/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '\n> @aragon/kits-beta@1.1.3 test /Users/xxx/xxx/dao-kits/kits/beta\n> npm run docker:build && npm run docker:run && test `docker-compose ps -q | xargs docker inspect -f \'{{ .Name }} {{ .State.ExitCode }}\' | grep deploy | cut -d\' \' -f 2` = 0\n\n\n> @aragon/kits-beta@1.1.3 docker:build /Users/xxx/xxx/dao-kits/kits/beta\n> docker build -t aragon/templates-beta -f Dockerfile ../..\n\n',
  stderr: 'time="2018-08-07T13:08:01+07:00" level=error msg="failed to dial gRPC: cannot connect to the Docker daemon. Is \'docker daemon\' running on this host?: dial unix /var/run/docker.sock: connect: no such file or directory" \ncontext canceled\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! @aragon/kits-beta@1.1.3 docker:build: `docker build -t aragon/templates-beta -f Dockerfile ../..`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @aragon/kits-beta@1.1.3 docker:build script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/tom/.npm/_logs/2018-08-07T06_08_01_382Z-debug.log\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! @aragon/kits-beta@1.1.3 test: `npm run docker:build && npm run docker:run && test `docker-compose ps -q | xargs docker inspect -f \'{{ .Name }} {{ .State.ExitCode }}\' | grep deploy | cut -d\' \' -f 2` = 0`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @aragon/kits-beta@1.1.3 test script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/tom/.npm/_logs/2018-08-07T06_08_01_414Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm run test',
  timedOut: false,
  exitCode: 1 }
npm ERR! Test failed.  See above for more details.
```

**Comment by tomtom87** [comment]
Found the issue with docker

**Comment by izqui** [comment]
What was causing the issue @tomtom87?
